### ISSUE TITLE
Greenhouse and Ginger Island still not working? 

### ISSUE THREAD

**Issue by MadnessBomber** [hawkfalcon/Stardew-Mods#58]
I downloaded 3.0.1 after finding that the Greenhouse and Ginger Island don't work, but they still don't.

Greenhouse, they do walk in, but then it's only one of them when I clearly see multiple walk in, and they don't do anything, they're just standing in the left-middle of the crops. Nothing gets harvested from it. I destroyed the crops around them to see if that does anything, but nope, they stand their with their hands in the air, occasionally jumping, but don't move from that spot. There's multiple ones as well, all clumped together. For clarification, I use the Bigger Greenhouse in Stardew Valley Expanded.

Ginger Island is even worse. Nothing happens. No Junimos at all. I stood there for a good 30 minutes in game, but they didn't budge. Clicked the hut, nothing. It was right in the middle of a big field of unharvested crops. This is my only mod that affects Ginger Island as far as I know.

This is my SMAPI log. https://smapi.io/log/bf09a59fe2744b8e8b5255a86a541232

**Comment by Hideman85** [comment]
Same issue here using the Submit's farm of Ridgeside, has also been reported by few users on the nexus post page with the same error log.

<details>

<summary>Error log</summary>

```
[game] An error occurred in the base update loop: System.Collections.Generic.Key
NotFoundException: The given key '00000000-0000-0000-0000-000000000000' was not 
present in the dictionary.
   at BetterJunimos.Utils.JunimoAbilities.<>c__DisplayClass18_0.<ItemInHut>b__0(
String item) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJuni
mos/Abilities/JunimoAbilities.cs:line 223
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate
)
   at BetterJunimos.Utils.JunimoAbilities.IdentifyJunimoAbility(GameLocation loc
ation, Vector2 pos, Guid hutGuid) in /Users/tristenmiller/Desktop/development/St
ardew-Mods/BetterJunimos/Abilities/JunimoAbilities.cs:line 123
   at BetterJunimos.Patches.PatchSearchAroundHut.SearchHutGrid(JunimoHut hut, In
t32 radius, GameLocation farm, Guid id) in /Users/tristenmiller/Desktop/developm
ent/Stardew-Mods/BetterJunimos/Patches/JunimoHutPatches.cs:line 109
   at BetterJunimos.Patches.PatchSearchAroundHut.SearchAroundHut(JunimoHut hut) 
in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Patches/J
unimoHutPatches.cs:line 46
   at BetterJunimos.Patches.PatchSearchAroundHut.Prefix(JunimoHut __instance, Bo
olean& __result) in /Users/tristenmiller/Desktop/development/Stardew-Mods/Better
Junimos/Patches/JunimoHutPatches.cs:line 36
   at StardewValley.Buildings.JunimoHut.areThereMatureCropsWithinRadius_PatchedB
y<com.hawkfalcon.BetterJunimos>(JunimoHut this)
   at StardewValley.Buildings.JunimoHut.updateWhenFarmNotCurrentLocation(GameTim
e time)
   at StardewValley.GameLocation.updateEvenIfFarmerIsntHere(GameTime time, Boole
an ignoreWasUpdatedFlush)
   at StardewValley.Game1._UpdateLocation_PatchedBy<leclair.bettercrafting>(Game
1 this, GameLocation location, GameTime time)
   at StardewValley.Game1.<>c__DisplayClass711_0.<UpdateLocations>b__0(GameLocat
ion location)
   at StardewValley.Utility.ForEachLocation(Func`2 action, Boolean includeInteri
ors, Boolean includeGenerated)
   at StardewValley.Game1.UpdateLocations(GameTime time)
   at StardewValley.Game1._update(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance,
 GameTime gameTime, Action runUpdate)
```

</details>

**Comment by Miguel-Thewolf** [comment]
https://github.com/Miguel-Thewolf/Stardew-Mods/tree/master

I tested it with Buildable Ginger Island and Grampleton Fields. Theoretically, it is compatible with the Build Anything Anywhere mod.

Pull request incoming
