### ISSUE TITLE
Junimo won't work when hut is built outside of farm

### ISSUE THREAD

**Issue by GitHub-Sysadmin** [hawkfalcon/Stardew-Mods#65]
Description of the bug:
When the Junimo Hut is built in locations outside the default farm area, such as Grampleton Field, the Junimo NPCs do not spawn to plant seeds from the hut. Despite providing fruit as payment and mixed seeds for planting, no action occurs.

Steps to reproduce:

    Build a Junimo Hut in a location outside the default farm area (e.g., Grampleton Field).
    Provide fruit as payment and place mixed seeds in the hut.
    Wait for the expected seed planting action, which does not occur.

Expected behavior:
Junimo NPCs should spawn and plant the seeds located in the Junimo Hut, regardless of the hut’s location on the map.

Actual behavior:
No Junimo NPCs spawn, and no seeds are planted when the Junimo Hut is built outside the default farm area.

Game version and mod version:

    Stardew Valley: 1.6(Latest version)
    Better Junimo: 3.0.0

Platform:
PC

SMAPI log:
https://smapi.io/log/7da19a94bdaa4437ad17688725846464

Screenshots or video
![StardewModdingAPI_xModI3wnSI](https://github.com/hawkfalcon/Stardew-Mods/assets/107381085/43b75050-ad7f-4026-835b-21372aaedc30)
![StardewModdingAPI_bWGK0Wpjh9](https://github.com/hawkfalcon/Stardew-Mods/assets/107381085/84abc2b7-37b9-4915-822f-e3c2413ddde0)

Other mods:
There are over 600 additional mods installed along with Better Junimo, none of which should conflict with this mod.

**Comment by GitHub-Sysadmin** [comment]
update: trying to open the status report of a junimo hut will give this error code: 
`[game] An error occurred in the base update loop: System.Collections.Generic.KeyNotFoundException: The given key '00000000-0000-0000-0000-000000000000' was not present in the dictionary.
   at BetterJunimos.Utils.JunimoAbilities.<>c__DisplayClass18_0.<ItemInHut>b__0(String item) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Abilities/JunimoAbilities.cs:line 223
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BetterJunimos.Utils.JunimoAbilities.IdentifyJunimoAbility(GameLocation location, Vector2 pos, Guid hutGuid) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Abilities/JunimoAbilities.cs:line 123
   at BetterJunimos.Patches.PatchSearchAroundHut.SearchHutGrid(JunimoHut hut, Int32 radius, GameLocation farm, Guid id) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Patches/JunimoHutPatches.cs:line 109
   at BetterJunimos.Patches.PatchSearchAroundHut.SearchAroundHut(JunimoHut hut) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Patches/JunimoHutPatches.cs:line 46
   at BetterJunimos.Patches.PatchSearchAroundHut.Prefix(JunimoHut __instance, Boolean& __result) in /Users/tristenmiller/Desktop/development/Stardew-Mods/BetterJunimos/Patches/JunimoHutPatches.cs:line 36
   at StardewValley.Buildings.JunimoHut.areThereMatureCropsWithinRadius_PatchedBy<com.hawkfalcon.BetterJunimos>(JunimoHut this)
   at StardewValley.Buildings.JunimoHut.updateWhenFarmNotCurrentLocation_PatchedBy<Spiderbuttons.ButtonsExtraBooksCore>(JunimoHut this, GameTime time)
   at StardewValley.GameLocation.updateEvenIfFarmerIsntHere(GameTime time, Boolean ignoreWasUpdatedFlush)
   at StardewValley.Game1._UpdateLocation_PatchedBy<leclair.bettercrafting>(Game1 this, GameLocation location, GameTime time)
   at StardewValley.Game1.<>c__DisplayClass711_0.<UpdateLocations>b__0(GameLocation location)
   at StardewValley.Utility.ForEachLocation(Func`2 action, Boolean includeInteriors, Boolean includeGenerated)
   at StardewValley.Game1.UpdateLocations(GameTime time)
   at StardewValley.Game1._update(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate)
`

**Comment by hawkfalcon** [comment]
I think this is now fixed
